# Generated by Django 6.0.3 on 2026-03-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
