# Generated by Django 6.0.3 on 2026-03-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_muscle_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='major_muscle_group',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Chest'), (1, 'Back'), (2, 'Shoulders'), (3, 'Legs'), (4, 'Arms'), (5, 'Core')], default=5),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
