# Generated by Django 6.0.3 on 2026-03-19 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_exercise_muscle_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
