# Generated by Django 6.0.3 on 2026-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='major_muscle_group',
            field=models.PositiveSmallIntegerField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Core', 'Core')], default=5),
        ),
    ]
