# Generated by Django 6.0.3 on 2026-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_exercise_major_muscle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='major_muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Core', 'Core')], default='Core'),
        ),
    ]
