# Generated by Django 6.0.3 on 2026-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_exercise_user_alter_exercise_major_muscle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='Weight in lbs', max_digits=4),
        ),
    ]
