# Generated by Django 6.0.3 on 2026-03-21 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_workoutset_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='WorkoutSession',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Resistance', 'Resistance'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Sport-specific', 'Sport-specific'), ('Other', 'Other')], default='Strength', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='Height in inches (in)', max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Weight in pounds (lbs)', max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
