# Generated by Django 6.0.3 on 2026-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_rename_workout_workoutsession_exercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutset',
            old_name='workout',
            new_name='session',
        ),
        migrations.AddField(
            model_name='workoutset',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='distance_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='duration_target',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='equipment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='modification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='positioning',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='reps_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='weight_target',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
