# Generated by Django 6.0.3 on 2026-03-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_rename_workout_workoutset_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Resistance', 'Resistance'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Sport-specific', 'Sport-specific'), ('Other', 'Other')], default='Resistance', max_length=20),
        ),
    ]
