# Generated by Django 6.0.3 on 2026-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='session_duration',
            field=models.DurationField(blank=True, help_text='Duration of the workout session', null=True),
        ),
    ]
