# Generated by Django 6.0.3 on 2026-03-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_workoutsession_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
